<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ModelCar extends Seeder
{
    public function run()
    {
        $data = [
            ['name'=>'Alfa Romeo','id_modelcar_parent'=>null],
            ['name'=>'Audi','id_modelcar_parent'=>null],
            ['name'=>'BMW','id_modelcar_parent'=>null],
            ['name'=>'Chevrolet','id_modelcar_parent'=>null],
            ['name'=>'Citroen','id_modelcar_parent'=>null],
            ['name'=>'Dacia','id_modelcar_parent'=>null],
            ['name'=>'Fiat','id_modelcar_parent'=>null],
            ['name'=>'Ford','id_modelcar_parent'=>null],
            ['name'=>'Honda','id_modelcar_parent'=>null],
            ['name'=>'Hyundai','id_modelcar_parent'=>null],
            ['name'=>'Isuzu','id_modelcar_parent'=>null],
            ['name'=>'Jaguar','id_modelcar_parent'=>null],
            ['name'=>'Jeep','id_modelcar_parent'=>null],
            ['name'=>'Kia','id_modelcar_parent'=>null],
            ['name'=>'Land Rover','id_modelcar_parent'=>null],
            ['name'=>'Mazda','id_modelcar_parent'=>null],
            ['name'=>'Mercedes','id_modelcar_parent'=>null],
            ['name'=>'Mitsubishi','id_modelcar_parent'=>null],
            ['name'=>'Nissan','id_modelcar_parent'=>null],
            ['name'=>'Opel','id_modelcar_parent'=>null],
            ['name'=>'Peugeot','id_modelcar_parent'=>null],
            ['name'=>'Renault','id_modelcar_parent'=>null],
            ['name'=>'Saab','id_modelcar_parent'=>null],
            ['name'=>'Seat','id_modelcar_parent'=>null],
            ['name'=>'Skoda','id_modelcar_parent'=>null],
            ['name'=>'Tesla','id_modelcar_parent'=>null],
            ['name'=>'Toyata','id_modelcar_parent'=>null],
            ['name'=>'Volkswagen','id_modelcar_parent'=>null],
            ['name'=>'Volvo','id_modelcar_parent'=>null],
            ['name'=>'Brera','id_modelcar_parent'=>1],
            ['name'=>'GT','id_modelcar_parent'=>1],
            ['name'=>'Giulia','id_modelcar_parent'=>1],
            ['name'=>'Giulietta','id_modelcar_parent'=>1],
            ['name'=>'A1','id_modelcar_parent'=>2],
            ['name'=>'A3','id_modelcar_parent'=>2],
            ['name'=>'A5','id_modelcar_parent'=>2],
            ['name'=>'A6','id_modelcar_parent'=>2],
            ['name'=>'A7','id_modelcar_parent'=>2],
            ['name'=>'TT','id_modelcar_parent'=>2],
            ['name'=>'I3','id_modelcar_parent'=>3],
            ['name'=>'I4','id_modelcar_parent'=>3],
            ['name'=>'Serie 3','id_modelcar_parent'=>3],
            ['name'=>'Serie 4','id_modelcar_parent'=>3],
            ['name'=>'Blazer','id_modelcar_parent'=>4],
            ['name'=>'Camaro','id_modelcar_parent'=>4],
            ['name'=>'Corvette','id_modelcar_parent'=>4],
            ['name'=>'2CV','id_modelcar_parent'=>5],
            ['name'=>'Berlingo','id_modelcar_parent'=>5],
            ['name'=>'C2','id_modelcar_parent'=>5],
            ['name'=>'C3','id_modelcar_parent'=>5],
            ['name'=>'C3 Picasso','id_modelcar_parent'=>5],
            ['name'=>'C3 Pluriel','id_modelcar_parent'=>5],
            ['name'=>'C4','id_modelcar_parent'=>5],
            ['name'=>'Jumpy','id_modelcar_parent'=>5],
            ['name'=>'Dokker','id_modelcar_parent'=>6],
            ['name'=>'Duster','id_modelcar_parent'=>6],
            ['name'=>'Jogger','id_modelcar_parent'=>6],
            ['name'=>'Lodgy','id_modelcar_parent'=>6],
            ['name'=>'Logan','id_modelcar_parent'=>6],
            ['name'=>'Sandero','id_modelcar_parent'=>6],
            ['name'=>'Spring','id_modelcar_parent'=>6],
            ['name'=>'Panda','id_modelcar_parent'=>7],
            ['name'=>'Punto','id_modelcar_parent'=>7],
            ['name'=>'500','id_modelcar_parent'=>7],
            ['name'=>'Fiesta','id_modelcar_parent'=>8],
            ['name'=>'Focus','id_modelcar_parent'=>8],
            ['name'=>'Galaxy','id_modelcar_parent'=>8],
            ['name'=>'Explorer','id_modelcar_parent'=>8],
            ['name'=>'Jazz','id_modelcar_parent'=>9],
            ['name'=>'Civic','id_modelcar_parent'=>9],
            ['name'=>'CRV','id_modelcar_parent'=>9],
        ];
        $this->db->table('modelcar')->insertBatch($data);
    }
}
